---
title: Elemental Concept
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@elementalconcept.com
description: Elemental Concept – Consultancy, Design, Prototype and Development
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
exclude:
- ".idea"
- ".idea/*"
